# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# MNIST Handwritten Digit Classification ✍️🔢

A deep-learning project that trains a Convolutional Neural Network (CNN) to classify handwritten digits from the MNIST dataset.

## Model Architecture
- Conv2D → ReLU
- MaxPooling
- Conv2D → ReLU
- Flatten
- Dense → Dense

## How to Run
pip install -r requirements.txt
python train.py

## Expected Accuracy
~98%+

## Files
- train.py → CNN training script
- mnist_cnn_model.h5 → Saved model (generated after running)